---
version: '3.8'

services:
  sc2-battle-experiments:
    build:
      context: .
    image: alvarofpp/sc2-battle-experiments
    container_name: sc2-battle-experiments
    ipc: host
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - WANDB_DOCKER=${WANDB_DOCKER}
      - WANDB_API_KEY=${WANDB_API_KEY}
